version: "3.8"
services:
  app:
    container_name: cyberCine_app
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - cyberCine-network
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - cyberCine-network
networks:
  cyberCine-network: